### ISSUE TITLE
Adding information about the ID

### ISSUE THREAD

**Issue by mhesselbarth** [equitable-equations/fqar#11]
https://github.com/openjournals/joss-reviews/issues/6366

It think it would be great to add some more information (very brief should be enough though) what the `database_id` is to the README so new users know how to find it when downloading data on their own. 

(Similar as in the help file of `download_assessment_list`)

**Comment by equitable-equations** [comment]
Done. The comment preceding the `download_assessment` example now reads:
> download a single assessment using the `assessment_id` assigned by
> [universalfqa.org](https://universalfqa.org/). These identifiers 
> can be found using `index_fqa_assessments`.
Good suggestion!
